### ISSUE TITLE
Match Screens to Mock-Ups 

### ISSUE THREAD

**Issue by vadini-agrawal** [GTBitsOfGood/bgc-safety#29]
Acceptance Criteria
1. Taking Bus Attendance Screen looks like the mockup 
https://www.figma.com/file/zbhSRm9PIJDcD7lDELS9jv/BGCMA-Wireframes-1?node-id=322%3A3482
2. Bus routes view screen look like the mockup (have it fill the page like the mockup) 
(screenshot attached) 
![Screen Shot 2020-03-09 at 7.59.05 PM.png](https://images.zenhubusercontent.com/5a620dd24b5806bc2bc36dc9/76a94f58-8415-4ab7-988f-192daa1ed4e2)
3. Make club directors attendance history screen look like the mockup 
(with the popup for individual student data) 
https://www.figma.com/file/zbhSRm9PIJDcD7lDELS9jv/BGCMA-Wireframes-1?node-id=331%3A806

**Comment by vadini-agrawal** [comment]
@emily-wilson Can you update the ticket based on what you've made already? Also, please push whatever progress you have!

**Comment by sauravghosal** [comment]
Dropping what I have so far for the bus routes screen!
![bus routes](https://user-images.githubusercontent.com/33039426/78418208-1e656980-7608-11ea-9cb8-736c5210b779.PNG)
This is the updated bus roster screen where the user can see all of the students checked in on a given bus route. I could not figure out how to align the headers of the bus and the school, so if someone could help me out with that, that would be great! The user can click on the "manual add entry" button at the bottom of each column to assign a student to a particular bus route. This pulls up the screen attached below.
![manual data entry](https://user-images.githubusercontent.com/33039426/78418211-232a1d80-7608-11ea-9582-40c6bb9dc3e2.PNG)
The user enters in all the required fields, and the student will be assigned to the bus route (not connected to backend yet) - but to set this up with the backend should be fairly simple.

**Comment by sauravghosal** [comment]
Here's what I have for the attendance history screen so far!
![attendance history](https://user-images.githubusercontent.com/33039426/78418238-72704e00-7608-11ea-895e-8ac5f1a7b654.PNG)
The UI for all the filters/dropdowns work, but they still need to be properly implemented and functional. The user can change the month with the date picker, and the appropriate student data will be pulled from the backend (shouldn't be too hard to set up). The student data displays as in the above image. I could not make the table itself scrollable, so if someone could help me out with that small change, that would be super nice.
![attendance history sorting](https://user-images.githubusercontent.com/33039426/78418284-d5fa7b80-7608-11ea-927a-31eed3995a3d.PNG)
The sorting functionality does work for alphabetical, grade, and low attendance, but something is wrong with the UI. It only sorts after the user clicks the button and then unclicks it. I want it to sort on button click - any guidance in this would be greatly appreciated!

**Comment by vadini-agrawal** [comment]
> Dropping what I have so far for the bus routes screen!
> ![bus routes](https://user-images.githubusercontent.com/33039426/78418208-1e656980-7608-11ea-9cb8-736c5210b779.PNG)
> This is the updated bus roster screen where the user can see all of the students checked in on a given bus route. I could not figure out how to align the headers of the bus and the school, so if someone could help me out with that, that would be great! The user can click on the "manual add entry" button at the bottom of each column to assign a student to a particular bus route. This pulls up the screen attached below.
> ![manual data entry](https://user-images.githubusercontent.com/33039426/78418211-232a1d80-7608-11ea-9582-40c6bb9dc3e2.PNG)
> The user enters in all the required fields, and the student will be assigned to the bus route (not connected to backend yet) - but to set this up with the backend should be fairly simple.

For aligning the columns, maybe the bus route name can be part of the same table as everything else?

**Comment by vadini-agrawal** [comment]
> Here's what I have for the attendance history screen so far!
> ![attendance history](https://user-images.githubusercontent.com/33039426/78418238-72704e00-7608-11ea-895e-8ac5f1a7b654.PNG)
> The UI for all the filters/dropdowns work, but they still need to be properly implemented and functional. The user can change the month with the date picker, and the appropriate student data will be pulled from the backend (shouldn't be too hard to set up). The student data displays as in the above image. I could not make the table itself scrollable, so if someone could help me out with that small change, that would be super nice.
> ![attendance history sorting](https://user-images.githubusercontent.com/33039426/78418284-d5fa7b80-7608-11ea-927a-31eed3995a3d.PNG)
> The sorting functionality does work for alphabetical, grade, and low attendance, but something is wrong with the UI. It only sorts after the user clicks the button and then unclicks it. I want it to sort on button click - any guidance in this would be greatly appreciated!

Don't worry about filtering for now. I'm glad sorting works though! @sauravghosal Can you DM the other front-end devs in Slack to get help with the button issue? If they don't know a fix I wouldn't spend too much time on it

**Comment by emily-wilson** [comment]
I just finished the calendar modal popup, it still needs to be connected to attendance history from the backend but here is what it looks like

<img width="873" alt="Screen Shot 2020-04-05 at 11 03 49 AM" src="https://user-images.githubusercontent.com/13021334/78502101-4d293000-772d-11ea-8836-a73cd0d67275.png">
