### ISSUE TITLE
Design Club Schema

### ISSUE THREAD

**Issue by Samyakkumar** [GTBitsOfGood/bgc-safety#3]
**Specs**
Fields: ClubName, List of Schools for each Club
Type: String, String, List 

**Acceptance Criteria**
1. Ability to add entries to database
2. Ability to modify entries in database
3. Ability to remove entries in database

**Comment by matthebrown** [comment]
@Samyakkumar The SchoolName and List of Schools fields seem contradictory. I'm assuming the correct field is the List but just wanted to confirm.

**Comment by Samyakkumar** [comment]
You are correct. I’ll fix the actual issue! Thanks for pointing that out!

**Comment by matthebrown** [comment]
One future consideration/discussion on this issue would be using regex validation to ensure that no special characters, double spaces, etc. are used.
