### ISSUE TITLE
Set up back-end for login 

### ISSUE THREAD

**Issue by vadini-agrawal** [GTBitsOfGood/bgc-safety#30]
**Specs** 
Fields for Schema: 
1. BGCMA_Email: String
2. Password: String 
3. userType: ["Admin", "ClubDirector", "BusDriver"]
4. Club: String, will be empty string for Admin userType 
APIs:
1. API for login verification of making sure: 
a) Email is in the table 
b) Password matches email 
c) Log-in type also matches email 
2. API for saving account information: would receive the schema fields above

**Comment by matthebrown** [comment]
@Samyakkumar Do we want to update the existing user schema for this? Perhaps changing the 'isAdmin' field to a 'Role' field that is an enum. Maybe something like ['Exec', 'Director', 'Driver'] ?

**Comment by vadini-agrawal** [comment]
He never responded lol but I think that makes sense! @matthewbrown77

**Comment by matthebrown** [comment]
There are a number of different options for configuring login. We could use a cookie-based approach, similar to the example in the next.js repo. We could also use something like the `next-session` package. I'm not sure if there is any type of "standard" approach that the club would like us to use. 

EDIT: The server already seems like it has existing jwt logic that we could leverage as well.

**Comment by vadini-agrawal** [comment]
Hmm if there is some existing logic that would make the job easier than go with that, all we need is for different user types/user profiles to be able to see only the data that is for them. Ideally a user would not have to log in every single time they open the website on a certain device, but if that is more difficult to implement it is not necessary. I guess in summary you can move forward with whatever you think would work best here. 

Also, @matthewbrown77 I just realized, could you add another field in the log-in schema for associated "Club"? For admin we can just say "All" and for everyone else they will have a String associated with which club they work at. Let me know if I should clarify anything.

**Comment by matthebrown** [comment]
I can add that field to the user schema. We can also decide how long we want sessions to last before expiring in our meeting tomorrow. It's a simple change to make.
