### ISSUE TITLE
Bus attendance history backend

### ISSUE THREAD

**Issue by vadini-agrawal** [GTBitsOfGood/bgc-safety#36]
Specs
1. API that returns # of days a student has been in attendance in that month (given a current date) 
 -- If necessary to supplement the above, an API that returns the current month (in number) given a current date 
2. API that returns the specific days a student has attended the club -> this might already be implemented

**Comment by abhijoshi2000** [comment]
Can you check on this issue with the attendance.js file? I'm pretty sure all this is already implemented
