### ISSUE TITLE
Connect Bus Attendance Entry & Adding Bus Route pages to Backend 

### ISSUE THREAD

**Issue by vadini-agrawal** [GTBitsOfGood/bgc-safety#48]
When the bus attendance entry and adding bus route pages are made in the front end (#1 on ticket https://github.com/GTBitsOfGood/bgc-safety/issues/29 and this ticket 5e41db83f3fb97e40f8ef551/board?repos=237324770, https://github.com/GTBitsOfGood/bgc-safety/issues/47), connect them to the back-end so that they show real data

**Comment by sauravghosal** [comment]
front end for the bus attendance entry pages is practically done, and now they just need to be connected to the backend. here are screenshots of how they look so far (i tried to make it as close to the mockups as possible)
route selection page
![image](https://user-images.githubusercontent.com/33039426/79053770-b9180680-7c0d-11ea-947f-e04e30527d7b.png)
bus attendance entry/check-in roster page
![image](https://user-images.githubusercontent.com/33039426/79053809-1449f900-7c0e-11ea-8bcb-5534317c1636.png)
adding/editing a note for a student
![image](https://user-images.githubusercontent.com/33039426/79053814-22981500-7c0e-11ea-9e50-dae7454682b2.png)
