### ISSUE TITLE
API to Retrieve School/Student Info 

### ISSUE THREAD

**Issue by vadini-agrawal** [GTBitsOfGood/bgc-safety#8]
Specs
1. Make an API that allows for the following:
a. Retrieve list of all schools 
b. Retrieve list of all students
c. Retrieve list of all students associated with a specific school 
d. Retrieve school for given student
e. Retrieve list of all schools with associated students

Acceptance Criteria 
1. API methods above are testable and work for dummy data given the current Student, School schemas

**Comment by matthebrown** [comment]
@emily-wilson will complete Tasks A and B. I will complete Tasks D and E. Task C will be left for whoever finishes their work first.

**Comment by matthebrown** [comment]
@emily-wilson I went ahead and completed requirement C so no need to repeat the work on your end.
